language: python

dist: bionic

python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8

install:
- pip install --upgrade pip setuptools
- pip install -r requirements-test.txt
- pip install .
- pip install coveralls

script:
- py.test -v --pep8 --cov pypsexec --cov-report term-missing

after_success:
- coveralls
